# AR parameters such as FFT parameters.
audio_repr: ar_byola.AR_BYOLAX
weight_file: external/byol_a/pretrained_weights/AudioNTT2020-BYOLA-64x96d2048.pth
feature_d: 2048
sample_rate: 16000
n_fft: 1024
window_size: 1024
hop_size: 160
n_mels: 64
f_min: 60
f_max: 7800
temporal_pooling_type: mean_max

# Training parameters.
batch_size: 256
lr_lineareval: 0.0003
report_per_epochs: 20
early_stop_epochs: 20

# Fine-tuning parameters.
## CAUTION: The following parameters not confirmed to work. ##
warmup_epochs: 5
mixup: 0.5
ft_bs: 256
ft_lr: 0.001
ft_early_stop_epochs: -1 # -1: no early stopping
ft_epochs: 200
ft_freq_mask: 30
ft_time_mask: 100
ft_rrc: True
