# AR parameters such as FFT parameters.
name: AR_COALA
audio_repr: ar_coala.AR_COALA
feature_d: 1152
sample_rate: 22000 # COALA Special
temporal_pooling_type: mean_max

# Training parameters.
batch_size: 64
lr_lineareval: 0.0003
report_per_epochs: 20
early_stop_epochs: 20
