# AR parameters such as FFT parameters.
audio_repr: ar_spec.AR_LinSpec
feature_d: 513
sample_rate: 16000
n_fft: 1024
window_size: 1024
hop_size: 160
#n_mels: 64
f_min: 60
f_max: 7800
temporal_pooling_type: mean_max

# Training parameters.
batch_size: 256
lr_lineareval: 0.0003
report_per_epochs: 20
early_stop_epochs: 20
