# AR parameters such as FFT parameters.
name: AR_TRILL
audio_repr: ar_trill.AR_TRILL
feature_d: 12288
sample_rate: 16000
temporal_pooling_type: mean_max

# Training parameters.
batch_size: 64
lr_lineareval: 0.0003
report_per_epochs: 20
early_stop_epochs: 20

# Model specific parameters.
trill_emb_type: layer19
# trill_emb_type: embedding
trill_url: https://tfhub.dev/google/nonsemantic-speech-benchmark/trill/2
