defaults:
  - default

predictor:
  _target_: src.models.components.stem_predictor.StemPredictor
  img_size: ${model.encoder.img_size}
  patch_size: ${model.encoder.patch_size}
  encoder_embed_dim: ${model.encoder.embed_dim}
  embed_dim: 512
  depth: 8
  num_heads: 16
  mlp_ratio: 4.
