# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints # directory to save the model file
  verbose: false # verbosity mode
  save_last: false # additionally always save an exact copy of the last checkpoint to a file last.ckpt
  save_top_k: -1 # save k best models (determined by above metric)
  mode: "min" # "max" means higher metric value is better, can be also "min"
  auto_insert_metric_name: True # when True, the checkpoints filenames will contain the metric name
  save_weights_only: true # if True, then only the model’s weights will be saved
  every_n_epochs: 50 # number of epochs between checkpoints
